/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.005
    progress_timeout: 500.0
    potential_scale: 5.0
    orientation_scale: 0.0
    gain_scale: 0.1
    transform_tolerance: 0.3
    min_frontier_size: 0.5
    sigma_unknown: 3.0
    sigma_known: 10.0
